### ISSUE TITLE
rdslogs doesn't handle binary data

### ISSUE THREAD

**Issue by dcposch** [honeycombio/rdslogs#19]
## setup
- standard MySQL 5.7 on RDS
- `rdslogs` running on EC2, set up exactly as described here: https://honeycomb.io/docs/connect/mysql/rds/
- note that I am using `utf8mb4` for most string columns, and i'm using `JSON` columns pretty extensively

## issue 
`rdslogs` finds my instance and begins tailing the slow query log.

however, it does not write any events to Honeycomb. instead, is just prints a lot of the same error message:

```
INFO[1445] binary data at marker 12:210510255, skipping 1000 in marker position

INFO[1445] binary data at marker 12:210511255, skipping 1000 in marker position

INFO[1445] binary data at marker 12:210512255, skipping 1000 in marker position

INFO[1445] binary data at marker 12:210513255, skipping 1000 in marker position

INFO[1445] binary data at marker 12:210514255, skipping 1000 in marker position
```

looks like the code that does this is here: https://github.com/honeycombio/rdslogs/blob/7676da69a07cce7d8160f565666eccb9ee597501/cli/cli.go#L164

**Comment by dcposch** [comment]
is there an easy way for me to get you a sample of my slow_query_log file for reference?

**Comment by tredman** [comment]
It looks like we're hitting this error when calling DownloadDBLogFilePortion:

> This file contains binary data and should be downloaded instead of viewed

We're consuming the error and kind of obfuscating it here. It's actually an error returned by the RDS service. I can't find a lot of documentation or AWS support about this. One theory I have based on some bits of info I read is that this is maybe due to `NumberOfLines * avg size of line` being greater than 1MB. In this case, AWS truncates the response down to 1MB. Maybe that's happening in an odd place causing AWS to interpret data incorrectly as binary?

By default we set NumberOfLines in our DownloadDBLogFilePortion to the max of 10000 to reduce the number of round trips needed to fetch the logs. Can you try setting `--num_lines=1000` or maybe even down to 100 and see if you still experience the same behavior?

**Comment by dcposch** [comment]
@tredman thanks! `--num_lines=1000` fixed it

might be worth changing the error message to suggest lowering `--num_lines`

**Comment by fbcbarbosa** [comment]
I'd just like to add that I keep hitting exactly the same issue with one particular rds mysql database. `--num_lines=1000` didn't fix it -- in fact, fact, I had to get `--num_lines=1` for it to work most of the times, and I'm _still_ getting "binary data at marker XXX, skipping 1000 in marker position" every now and then.

I _think_ there might be something horribly wrong with this database :p we have these settings:

```
log_output to FILE
slow_query_log to 1
long_query_time to 0.1
log_queries_not_using_indexes to 1
```
In this particular database the queries are all generated by an ORM, and I know that a lot of them are particularly large, which might explain the issue. I'll drill down more into this latest but I'm worried because running it with `--num_lines=1` makes ingestion very, very slow.
