### ISSUE TITLE
Error: "version number does not start with digit" on package install 

### ISSUE THREAD

**Issue by aleksmark** [honeycombio/rdslogs#54]
**Versions**
1.135

**Steps to reproduce**

1. download deb package 
`curl --location --get https://honeycomb.io/download/rdslogs/rdslogs_1.135_amd64.deb -O`
2. install package with dpkg
`dpkg -i rdslogs_1.135_amd64.deb`

**Additional context**

the output of `dpkg -i rdslogs_1.135_amd64.deb`
```
dpkg: error processing archive rdslogs_1.135_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'rdslogs':
 'Version' field value 'v1.135.0': version number does not start with digit
Errors were encountered while processing:
 rdslogs_1.135_amd64.deb
 ```

**Comment by kentquirk** [comment]
Sigh. I apologize, @aleksmark. Clearly I'm not familiar with Debian packaging rules. I would have thought that the `fpm` packaging script would have warned me about things like this. I honestly don't know exactly what I have to do to make this work, though, and it's not easy for me to test it. 

Our telemetry shows that there is literally only one team (presumably you) who has used this tool in the last several months, which is why we are sunsetting it and it's hard to justify spending much more time on it. Are you in a position to build it yourself, or at least use a non-packaged binary? Our build process did build a binary and upload it; we could make that available to you without the surrounding package.

**Comment by aleksmark** [comment]
Hi @kentquirk, first let me thank you for the work done so far on issues #48 and #53 . 

Unfortunately, we don't have anybody in the team who can build it, at least not without investing time and learning how to do it. 

Let's try with the binary, I would appreciate if you send it to me. Thank you.

**Comment by kentquirk** [comment]
Please try [this URL](https://s3.amazonaws.com/honeycomb-builds/honeycombio/rdslogs/v1.135.0/rdslogs-linux-amd64). There are also binaries for arm64, arm, and 386 if you substitute those strings at the end.

**Comment by aleksmark** [comment]
@kentquirk binary file is working for us. Thank you

**Comment by kentquirk** [comment]
👍
